/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wsgh_androidutils_mp3lame_MP3LameUtils */

#ifndef _Included_com_wsgh_androidutils_mp3lame_MP3LameUtils
#define _Included_com_wsgh_androidutils_mp3lame_MP3LameUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wsgh_androidutils_mp3lame_MP3LameUtils
 * Method:    initEncoder
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_wsgh_androidutils_mp3lame_MP3LameUtils_initEncoder
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_wsgh_androidutils_mp3lame_MP3LameUtils
 * Method:    destroyEncoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wsgh_androidutils_mp3lame_MP3LameUtils_destroyEncoder
  (JNIEnv *, jobject);

/*
 * Class:     com_wsgh_androidutils_mp3lame_MP3LameUtils
 * Method:    encodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wsgh_androidutils_mp3lame_MP3LameUtils_encodeFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
